title: Chimie PCSI Faidherbe
remote_theme: BDHU/minimalist
plugins:
  - jekyll-remote-theme
color-scheme: dark

logo: /assets/images/logo.png
favicon: true

sidebar:
  
  - name: Accueil
    icon: <i class="fa-solid fa-house"></i>
    link: /chimie_pcsi/

  - name: Cours & Exercices
    icon: <i class="fa-solid fa-book"></i>
    link: ""    

  - name: "> Transformations de la matière"
    icon: <i class="fa-solid fa-circle" style="opacity:0"></i>
    link: /chimie_pcsi/TM/

  - name: "> Architecture de la matière"
    icon: <i class="fa-solid fa-circle" style="opacity:0"></i>
    link: /chimie_pcsi/

  - name: "> Chimie Organique"
    icon: <i class="fa-solid fa-circle" style="opacity:0"></i>
    link: /
      
  - name: "> Solutions Aqueuses"
    icon: <i class="fa-solid fa-circle" style="opacity:0"></i>
    link: /

  - name: Travaux Pratiques
    icon: <i class="fa-solid fa-flask"></i>
    link: /

  - name: Cahier de texte
    icon: <i class="fa-solid fa-calendar"></i>
    link: /
