title: Chimie PCSI Faidherbe
remote_theme: BDHU/minimalist@f19d6a6
plugins:
  - jekyll-remote-theme
color-scheme: dark

logo: /assets/images/logo.png
favicon: true

sidebar:
  
  - name: Accueil
    icon: <i class="fa-solid fa-house"></i>
    link: /chimie_pcsi/

  - name: Cours & Exercices
    icon: <i class="fa-solid fa-book"></i>
    link: ""    

  - name: "> Transformations de la matière"
    icon: <i class="fa-solid fa-circle" style="opacity:0"></i>
    link: /chimie_pcsi/TM/

  - name: "> Architecture de la matière"
    icon: <i class="fa-solid fa-circle" style="opacity:0"></i>
    link: /chimie_pcsi/AM/

  - name: "> Chimie Organique"
    icon: <i class="fa-solid fa-circle" style="opacity:0"></i>
    link: /chimie_pcsi/CO/
      
  - name: "> Solutions Aqueuses"
    icon: <i class="fa-solid fa-circle" style="opacity:0"></i>
    link: /chimie_pcsi/SA/

  - name: Travaux Pratiques
    icon: <i class="fa-solid fa-flask"></i>
    link: /chimie_pcsi/TP/

  - name: Cahier de texte
    icon: <i class="fa-solid fa-calendar"></i>
    link: /chimie_pcsi/CT/

  - name: Annonces
    icon: <i class="fa-solid fa-bullhorn"></i>
    link: /chimie_pcsi/AN/

  - name: Programme de colles
    icon: <i class="fa-solid fa-calendar-check"></i>
    link: /chimie_pcsi/PC/

  - name: Scripts Python
    icon: <i class="fa-solid fa-code"></i>
    link: /chimie_pcsi/PY/