name: Déployer sur GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Installer les dépendances
        run: |
          gem install bundler
          bundle install || true

      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
          exclude_assets: '.nojekyll'
          keep_files: false
